// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
  path: "prisma/migrations",
  seed: "bun ./prisma/seed.ts",
},
  datasource: {
    url: process.env["DATABASE_URL"] || "postgresql://postgres:Prem004@127.0.0.1:5432/helpdesk",
  },
});
